import Foundation

/// Filters harness machinery out of a transcript.
///
/// Agent harnesses inject transport into the conversation as user-role turns:
/// system reminders, hook output, slash-command envelopes, local-command
/// caveats. These are not something the user typed, so a viewer must not show
/// them as prompts.
///
/// The match list is deliberately narrow. Only tag names actually observed from
/// harnesses count; a genuine prompt that happens to start with a custom
/// `<my-element>` stays a real user turn, because hiding a real turn is a worse
/// failure than showing one line of machinery.
enum AgentTranscriptNoise {
    /// Leading tags observed from Claude Code and its forks.
    static let harnessTagNames: Set<String> = [
        "agent-message",
        "bash-input",
        "bash-stderr",
        "bash-stdout",
        "command-args",
        "command-message",
        "command-name",
        "cross-session-message",
        "local-command-caveat",
        "local-command-stderr",
        "local-command-stdout",
        "system-reminder",
        "task-notification",
        "user-memory-input",
        "user-prompt-submit-hook",
    ]

    /// Injected turns identified by a leading phrase rather than a tag.
    static let harnessPrefixes = [
        "[request interrupted",
        "caveat: the messages below were generated by the user while running local commands",
        "this session is being continued from a previous conversation",
    ]

    /// Classification only inspects the head of the text, so a multi-megabyte
    /// paste never pays for a full lowercased copy.
    static let classificationHeadCharacters = 256

    static func isHarnessInjectedText(_ text: String) -> Bool {
        let head = String(
            text.trimmingCharacters(in: .whitespacesAndNewlines).prefix(classificationHeadCharacters)
        ).lowercased()
        guard !head.isEmpty else {
            return false
        }
        if harnessPrefixes.contains(where: head.hasPrefix) {
            return true
        }
        guard let tag = leadingTagName(in: head) else {
            return false
        }
        return harnessTagNames.contains(tag)
    }

    /// `<system-reminder>` or `<system-reminder attr=...>` yields
    /// `system-reminder`; anything else yields `nil`.
    static func leadingTagName(in lowercasedHead: String) -> String? {
        guard lowercasedHead.hasPrefix("<") else {
            return nil
        }
        var name = ""
        for character in lowercasedHead.dropFirst() {
            if character == ">" || character.isWhitespace {
                break
            }
            let isNameCharacter = character.isLowercase || character.isNumber || character == "-"
            guard isNameCharacter else {
                return nil
            }
            name.append(character)
        }
        guard let first = name.first, first.isLetter, !name.isEmpty else {
            return nil
        }
        return name
    }

    /// A message is noise only when it is a prose-only user or system turn that
    /// matches an observed harness shape. Tool calls and results are never
    /// noise: they are the agent's real work.
    static func isNoise(_ message: AgentTranscriptMessage) -> Bool {
        guard message.role == .user || message.role == .system else {
            return false
        }
        guard !message.blocks.contains(where: \.isTool) else {
            return false
        }
        return isHarnessInjectedText(message.text)
    }

    static func stripped(_ messages: [AgentTranscriptMessage]) -> [AgentTranscriptMessage] {
        messages.filter { !isNoise($0) }
    }
}
